- id: 10.1093/nargab/lqag026
  title: "MycoMobilome: a community-focused non-redundant database of transposable element consensus sequences for the fungal kingdom"
  authors:
  - Tobias Baril
  - Daniel Croll
  publisher: NAR Genomics and Bioinformatics
  date: '2026-03-05'
  link: https://doi.org/10.1093/nargab/lqag026
  orcid: 0000-0002-5936-7531
  image: images/projects/mycomobilome.png
  tags:
  - transposable elements
  - fungi
  - resources
  - database
  - github
  - TE diversity and evolution
- id: doi:10.1101/2025.10.28.685023
  remove: true
- id: doi:10.1101/2022.09.21.508825
  remove: true
- id: doi:10.1101/2020.03.03.972679
  remove: true
- id: doi:10.1101/2020.04.16.045815
  remove: true
- title: A draft genome sequence of the elusive giant squid, Architeuthis dux
  date: '2022-05-29'
  link: http://hdl.handle.net/10871/39675
  orcid: 0000-0002-5936-7531
  plugin: orcid.py
  file: orcid.yaml
  remove: true
- id: doi:10.1093/gigascience/giac012
  remove: true
- id: pmid:35166339
  title: "Genome of the ramshorn snail Biomphalaria straminea—an obligate intermediate host of schistosomiasis"
  authors:
  - Wenyan Nong
  - Yifei Yu
  - Madeleine E Aase-Remedios
  - Yichun Xie
  - Wai Lok So
  - Yiqian Li
  - Cheuk Fung Wong
  - Tobias Baril
  - Sean T S Law
  - Sheung Yee Lai
  - Jasmine Haimovitz
  - Thomas Swale
  - Shan-shan Chen
  - Zhen-peng Kai
  - Xi Sun
  - Zhongdao Wu
  - Alexander Hayward
  - David E K Ferrier
  - Jerome H L Hui
  publisher: GigaScience
  date: '2022-02-15'
  link: https://academic.oup.com/gigascience/article/doi/10.1093/gigascience/giac012/6528774
  orcid: 0000-0002-5936-7531
  image: images/publications/giac012.jpeg
  tags:
  - genome
  - transposable elements
  - molluscs
- id: doi:10.1093/gigascience/giz152
  date: '2020-01-16'
  image: images/publications/giz152.jpeg
  tags:
  - genome
  - transposable elements
  - molluscs
- id: doi:10.64898/2026.06.15.732387
  image: images/publications/2026.06.15.732387.jpg
  tags:
  - transposable elements
  - lepidoptera
  - comparative genomics
- id: doi:10.1093/gbe/evag017
  image: images/publications/evag017.jpeg
  tags:
  - fungi
  - genome
  - transposable elements
- id: doi:10.1016/j.cub.2025.11.062
  image: images/publications/j.cub.2025.11.062.jpg
  tags:
  - dispatch
  - transposable elements
  - fungi
- id: doi:10.1016/j.tim.2025.07.006
  image: images/publications/j.tim.2025.07.006.jpg
  date: '2025-08-07'
  tags:
  - fungi
  - transposable elements
  - hypermutation
  - opinion
- id: doi:10.1038/s41467-025-64944-4
  image: images/publications/s41467-025-64944-4.jpeg
  tags:
  - transposable elements
  - TE diversity and evolution
  - population genomics
  - fungi
- id: doi:10.1038/s41598-025-19494-6
  image: images/publications/s41598-025-19494-6.jpeg
  tags:
  - arthropods
  - transposable elements
  - resistance evolution
- id: doi:10.1016/j.ibmb.2025.104403
  image: images/publications/j.ibmb.2025.104403.jpg
  tags:
  - experimental evolution
  - transposable elements
  - arthropods
  - resistance evolution
- id: doi:10.1093/molbev/msae197
  image: images/publications/msae197.jpeg
  tags:
  - fungi
  - genome
  - transposable elements
  - domestication
- id: doi:10.1093/GBE/EVAE049
  image: images/publications/EVAE049.jpeg
  tags:
  - birds
  - structural variation
  - resources
- id: doi:10.1093/MOLBEV/MSAE068
  image: images/highlights/earlgrey.png
  tags:
  - transposable elements
  - TE diversity and evolution
  - resources
  - software
  - github
  - annotation
- id: doi:10.1093/MOLBEV/MSAE246
  image: images/publications/MSAE246.jpeg
  tags:
  - sharks
  - genome
  - transposable elements
- id: doi:10.1101/gr.277820.123
  image: images/publications/gr.277820.123.jpg
  tags:
  - comparative genomics
  - transposable elements
  - arthropods
  - TE diversity and evolution
- id: doi:10.1093/MOLBEV/MSAD115
  image: images/publications/MSAD115.jpeg
  tags:
  - genome
  - transposable elements
  - mammals
- id: doi:10.1186/S13104-023-06613-7
  image: images/publications/S13104-023-06613-7.jpeg
  tags:
  - transposable elements
  - resources
  - database
- id: doi:10.1186/S12915-023-01703-1
  image: images/publications/S12915-023-01703-1.jpeg
  tags:
  - genome
  - lepidoptera
  - transposable elements
- id: doi:10.1016/j.ygeno.2022.110440
  image: images/publications/j.ygeno.2022.110440.jpg
  tags:
  - genome
  - lepidoptera
  - transposable elements
- id: doi:10.1038/s41467-022-30690-0
  image: images/publications/s41467-022-30690-0.jpeg
  tags:
  - genome
  - arthropods
  - comparative genomics
  - transposable elements
- id: doi:10.1093/g3journal/jkac069
  image: images/publications/jkac069.jpeg
  tags:
  - genome
  - lepidoptera
  - transposable elements
- id: doi:10.1186/s13100-022-00263-5
  image: images/publications/s13100-022-00263-5.jpeg
  tags:
  - transposable elements
  - lepidoptera
  - TE diversity and evolution
  - comparative genomics
- id: doi:10.1111/MEC.16588
  image: images/publications/MEC.16588.jpg
  tags:
  - transcriptomics
  - genome
  - transposable elements
  - arthropods
- id: doi:10.1093/G3JOURNAL/JKAC193
  image: images/publications/JKAC193.jpeg
  tags:
  - genome
  - lepidoptera
  - transposable elements
- id: doi:10.12688/wellcomeopenres.17280.1
  image: images/publications/wellcomeopenres.17280.1.jpg
  tags:
  - genome
  - lepidoptera
  - transposable elements
- id: doi:10.1101/2021.09.26.461848
  image: images/publications/2021.09.26.461848.jpg
  tags:
  - transposable elements
  - TE diversity and evolution
- id: doi:10.1038/S42003-020-01637-2
  image: images/publications/S42003-020-01637-2.jpeg
  tags:
  - genome
  - transposable elements
  - arthropods
- id: doi:10.1186/s12864-020-07145-1
  image: images/publications/s12864-020-07145-1.jpeg
  tags:
  - genome
  - transposable elements
  - fish
- id: doi:10.1186/s13100-020-00212-0
  image: images/publications/s13100-020-00212-0.jpeg
  tags:
  - transposable elements
  - TE diversity and evolution
- id: doi:10.1186/s12864-020-07027-6
  image: images/publications/s12864-020-07027-6.jpeg
  tags:
  - genome
  - transposable elements
  - molluscs
- id: doi:10.1371/journal.pbio.3000636
  image: images/publications/journal.pbio.3000636.png
  tags:
  - genome
  - transposable elements
  - arthropods
  - comparative genomics
- id: doi:10.1111/1755-0998.13154
  image: images/publications/1755-0998.13154.jpeg
  date: '2020-03-10'
  tags:
  - genome
  - transposable elements
  - plants
- id: doi:10.64898/2026.07.21.739809
  title: Comparative analyses reveal rapid turnover and emergence of transitory 3D genome architectures in the fungal kingdom
  authors:
  - Alice Laigle
  - Camille Cornet
  - Ashwini V. Mohan
  - Tobias Baril
  - Daniel Croll
  publisher: openRxiv
  date: '2026-07-21'
  link: https://doi.org/10.64898/2026.07.21.739809
  image: images/publications/2026.07.21.739809.jpg
  tags:
  - comparative genomics
  - fungi
  - structural variation
  - transposable elements


